# Generated by Django 3.1.5 on 2021-01-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPolicyDetails',
            fields=[
                ('policy_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
                ('customer_id', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=15)),
                ('vehicle_segment', models.CharField(max_length=1)),
                ('premium', models.IntegerField()),
                ('bodily_injury_liability', models.CharField(max_length=1)),
                ('personal_injury_protection', models.CharField(max_length=1)),
                ('property_damage_liability', models.CharField(max_length=1)),
                ('collision', models.CharField(max_length=1)),
                ('comprehensive', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=6)),
                ('income_group', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=1)),
            ],
        ),
    ]
